//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSPToolsVS.Project.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSPToolsVS.Project.Resources.ProjectResources", typeof(ProjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add Reference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddReferenceDialogTitle {
            get {
                return ResourceManager.GetString("AddReferenceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **AddReferenceExtensions** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddReferenceExtensions {
            get {
                return ResourceManager.GetString("AddReferenceExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to add file &apos;{0}&apos; to project as project is null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddToNullProjectError {
            get {
                return ResourceManager.GetString("AddToNullProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not load attribute &apos;{0}&apos; from project file &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AttributeLoad {
            get {
                return ResourceManager.GetString("AttributeLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build Action に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BuildAction {
            get {
                return ResourceManager.GetString("BuildAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How the file relates to the build and deployment process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BuildActionDescription {
            get {
                return ResourceManager.GetString("BuildActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BuildCaption {
            get {
                return ResourceManager.GetString("BuildCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception was thrown during BuildBegin event\n{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BuildEventError {
            get {
                return ResourceManager.GetString("BuildEventError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Verbosity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BuildVebosity {
            get {
                return ResourceManager.GetString("BuildVebosity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify how much information is included the build output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BuildVerbosityDescription {
            get {
                return ResourceManager.GetString("BuildVerbosityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The command you are attempting cannot be completed because the file &apos;{0}&apos; that must be modified cannot be changed. If the file is under source control, you may want to check it out; if the file is read-only on disk, you may want to change its attributes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelQuertEdit {
            get {
                return ResourceManager.GetString("CancelQuertEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The command you are attempting cannot be completed because the files &apos;{0}&apos; that must be modified cannot be changed. If the file is under source control, you may want to check it out; if the file is read-only on disk, you may want to change its attributes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelQueryEditMultiple {
            get {
                return ResourceManager.GetString("CancelQueryEditMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **CannotAddAsDescendantOfSelf** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotAddAsDescendantOfSelf {
            get {
                return ResourceManager.GetString("CannotAddAsDescendantOfSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A file with name &apos;{0}&apos; already exists. Please give a unique name to the item you are adding, or delete the existing item first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotAddFileExists {
            get {
                return ResourceManager.GetString("CannotAddFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A file with name &apos;{0}&apos; already exists and is open in an editor. Please give a unique name to the item you are adding, or delete the existing item first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotAddFileThatIsOpenInEditor {
            get {
                return ResourceManager.GetString("CannotAddFileThatIsOpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A folder with name &apos;{0}&apos; already exists. Please give a unique name to the item you are adding, or delete the existing item first. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotMoveFolderExists {
            get {
                return ResourceManager.GetString("CannotMoveFolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **CannotMoveIntoSameDirectory** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotMoveIntoSameDirectory {
            get {
                return ResourceManager.GetString("CannotMoveIntoSameDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **CannotMoveIntoSubfolder** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotMoveIntoSubfolder {
            get {
                return ResourceManager.GetString("CannotMoveIntoSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **CanNotSaveFileNotOpeneInEditor** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanNotSaveFileNotOpeneInEditor {
            get {
                return ResourceManager.GetString("CanNotSaveFileNotOpeneInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ECMA-335 CLI compatible framework (location must be provided) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cli1 {
            get {
                return ResourceManager.GetString("cli1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Compile に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Compile {
            get {
                return ResourceManager.GetString("Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you change a file name extension, the file may become unusable. Are you sure you want to change it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmExtensionChange {
            get {
                return ResourceManager.GetString("ConfirmExtensionChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Content に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy To Local に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyToLocal {
            get {
                return ResourceManager.GetString("CopyToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indicates whether the reference will be copied to the output directory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyToLocalDescription {
            get {
                return ResourceManager.GetString("CopyToLocalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Tool に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomTool {
            get {
                return ResourceManager.GetString("CustomTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the tool that transforms a file at design time and places the output of that transformation into another file. For example, a dataset (.xsd) file comes with a default custom tool. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomToolDescription {
            get {
                return ResourceManager.GetString("CustomToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom Tool Namespace に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomToolNamespace {
            get {
                return ResourceManager.GetString("CustomToolNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The namespace into which the output of the custom tool is placed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomToolNamespaceDescription {
            get {
                return ResourceManager.GetString("CustomToolNamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detailed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Detailed {
            get {
                return ResourceManager.GetString("Detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An &apos;Import&apos; of the file &apos;{1}&apos; was found in the project file &apos;{0}&apos;. This file is not registered as a safe file to import, and could contain targets and tasks that are harmful.  If this imported file is indeed considered safe, then it can be registered by writing to the registry key {2}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetailsImport {
            get {
                return ResourceManager.GetString("DetailsImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One or more items named &apos;{1}&apos; were found in the project file &apos;{0}&apos;. These items normally should not be specified in the project file. They can change the way targets and tasks are executed during project load, and this could have harmful effects. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetailsItem {
            get {
                return ResourceManager.GetString("DetailsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An item referring to the file &apos;{1}&apos; was found in the project file &apos;{0}&apos;.  Since this file is located within a system directory, root directory, or network share, it could be harmful to write to this file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetailsItemLocation {
            get {
                return ResourceManager.GetString("DetailsItemLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A property named &apos;{1}&apos; was found in the project file &apos;{0}&apos;.  This property normally should not be specified in the project file.  Its value can change the way targets and tasks are executed during project load, and this could have harmful effects. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetailsProperty {
            get {
                return ResourceManager.GetString("DetailsProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A &apos;Target&apos; named &apos;{1}&apos; was found in the project file &apos;{0}&apos;.  The tasks within this target could contain arbitrary code and may get executed as soon as the project is loaded in the IDE. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetailsTarget {
            get {
                return ResourceManager.GetString("DetailsTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An &apos;Import&apos; of the file &apos;{1}&apos; was found in the user project file &apos;{0}&apos;.  All imports in user project files are considered unsafe. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetailsUserImport {
            get {
                return ResourceManager.GetString("DetailsUserImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A &apos;UsingTask&apos; tag which registers the &apos;{1}&apos; task was found in the project file &apos;{0}&apos;.  &apos;UsingTask&apos; tags in the project file take precedence over those in the imported .TARGETS files, and therefore could be used to execute arbitrary code during an otherwise unmodified build process. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DetailsUsingTask {
            get {
                return ResourceManager.GetString("DetailsUsingTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diagnostic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Diagnostic {
            get {
                return ResourceManager.GetString("Diagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryExists {
            get {
                return ResourceManager.GetString("DirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirectoryExistsShortMessage {
            get {
                return ResourceManager.GetString("DirectoryExistsShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error opening specified view &apos;{0}&apos; using editor &apos;{1}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EditorViewError {
            get {
                return ResourceManager.GetString("EditorViewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Embedded Resource に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmbeddedResource {
            get {
                return ResourceManager.GetString("EmbeddedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **ErrorDetail** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorDetail {
            get {
                return ResourceManager.GetString("ErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid filename: {0}
        ///      
        ///Files and folders cannot be:
        ///- Empty strings 
        ///- System reserved names, including &apos;CON&apos;, &apos;AUX&apos;, PRN&apos;, &apos;COM1&apos; or &apos;LPT2&apos; 
        ///- contain only &apos;.&apos;
        ///- have any of the following characters: / ? : &amp;  \ * &quot; &lt; &gt; | # % に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidFileName {
            get {
                return ResourceManager.GetString("ErrorInvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid launchurl: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidLaunchUrl {
            get {
                return ResourceManager.GetString("ErrorInvalidLaunchUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name you provided is not a valid project name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorInvalidProjectName {
            get {
                return ResourceManager.GetString("ErrorInvalidProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MSBuild path not found in registry. Please reinstall to fix the problem. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorMsBuildRegistration {
            get {
                return ResourceManager.GetString("ErrorMsBuildRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A reference to {0} could not be added. Please make sure that the file is accessible, and that it is a valid assembly or COM component. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorReferenceCouldNotBeAdded {
            get {
                return ResourceManager.GetString("ErrorReferenceCouldNotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Saving File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Console Application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exe {
            get {
                return ResourceManager.GetString("Exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Expecting object of type {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExpectedObjectOfType {
            get {
                return ResourceManager.GetString("ExpectedObjectOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to retrieve MSBuild property {0} from the project file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedToRetrieveProperties {
            get {
                return ResourceManager.GetString("FailedToRetrieveProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A file with the same name &apos;{0}&apos; already exists. Do you want to overwrite it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A file with the same name &apos;{0}&apos; already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileAlreadyExistsAndCannotBeRenamed {
            get {
                return ResourceManager.GetString("FileAlreadyExistsAndCannotBeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination File Exists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileAlreadyExistsCaption {
            get {
                return ResourceManager.GetString("FileAlreadyExistsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A file of this name is already part of the project. Do you want to overwrite it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileAlreadyInProject {
            get {
                return ResourceManager.GetString("FileAlreadyInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Destination File Exists に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileAlreadyInProjectCaption {
            get {
                return ResourceManager.GetString("FileAlreadyInProjectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A file or folder with the name &apos;{0}&apos; already exists on disk at this location. Please choose another name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileCannotBeRenamedToAnExistingFile {
            get {
                return ResourceManager.GetString("FileCannotBeRenamedToAnExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error Copying File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileCopyError {
            get {
                return ResourceManager.GetString("FileCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File and folder names cannot contain a leading period. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameCannotContainALeadingPeriod {
            get {
                return ResourceManager.GetString("FileNameCannotContainALeadingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the file or folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileNameDescription {
            get {
                return ResourceManager.GetString("FileNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **FileOpenDoesNotExist** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileOpenDoesNotExist {
            get {
                return ResourceManager.GetString("FileOpenDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A file or folder with the name &apos;{0}&apos; already exists on disk at this location. Please choose another name. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileOrFolderAlreadyExists {
            get {
                return ResourceManager.GetString("FileOrFolderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The item &apos;{0}&apos; cannot be found on disk, either because it has been renamed, deleted, or moved to a new location. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileOrFolderCannotBeFound {
            get {
                return ResourceManager.GetString("FileOrFolderCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FileProperties {
            get {
                return ResourceManager.GetString("FileProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **FolderCannotBeCreatedOnDisk** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderCannotBeCreatedOnDisk {
            get {
                return ResourceManager.GetString("FolderCannotBeCreatedOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name of this folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderNameDescription {
            get {
                return ResourceManager.GetString("FolderNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **FolderPathTooLongShortMessage** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderPathTooLongShortMessage {
            get {
                return ResourceManager.GetString("FolderPathTooLongShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FolderProperties {
            get {
                return ResourceManager.GetString("FolderProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FullPath {
            get {
                return ResourceManager.GetString("FullPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location of the file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FullPathDescription {
            get {
                return ResourceManager.GetString("FullPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Automation object invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidAutomationObject {
            get {
                return ResourceManager.GetString("InvalidAutomationObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid logger type\nExpected: {0}\nReceived: {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidLoggerType {
            get {
                return ResourceManager.GetString("InvalidLoggerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InvalidParameter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The item &apos;{0}&apos; does not exist in the project directory. It may have been moved, renamed or deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ItemDoesNotExistInProjectDirectory {
            get {
                return ResourceManager.GetString("ItemDoesNotExistInProjectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LaunchUrl {
            get {
                return ResourceManager.GetString("LaunchUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The URL which should be opened in the browser when launching the project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LaunchUrlDescription {
            get {
                return ResourceManager.GetString("LaunchUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Class Library に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot save &apos;{0}&apos; outside the project directory. Linked items are not supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LinkedItemsAreNotSupported {
            get {
                return ResourceManager.GetString("LinkedItemsAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Minimal {
            get {
                return ResourceManager.GetString("Minimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Misc に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The nested project has failed to reload. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NestedProjectFailedToReload {
            get {
                return ResourceManager.GetString("NestedProjectFailedToReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputPath {
            get {
                return ResourceManager.GetString("OutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path to the primary output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputPathDescription {
            get {
                return ResourceManager.GetString("OutputPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **OverwriteFilesInExistingFolder** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OverwriteFilesInExistingFolder {
            get {
                return ResourceManager.GetString("OverwriteFilesInExistingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **ParameterCannotBeNullOEmpty** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParameterCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ParameterCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter must be a valid guid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParameterMustBeAValidGuid {
            get {
                return ResourceManager.GetString("ParameterMustBeAValidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter must be a valid item identifier. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ParameterMustBeAValidItemId {
            get {
                return ResourceManager.GetString("ParameterMustBeAValidItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item is not available or corrupted and thus cannot be pasted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PasteFailed {
            get {
                return ResourceManager.GetString("PasteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The complete path to &apos;{0}&apos; exceeds the maximum number of characters permitted by the file system. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathTooLong {
            get {
                return ResourceManager.GetString("PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The filename or extension is too long. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathTooLongShortMessage {
            get {
                return ResourceManager.GetString("PathTooLongShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A reference to library &apos;{0}&apos; cannot be added. Adding this project as a reference would cause a circular dependency. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectContainsCircularReferences {
            get {
                return ResourceManager.GetString("ProjectContainsCircularReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the file containing build, configuration, and other information about the project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectFileDescription {
            get {
                return ResourceManager.GetString("ProjectFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectFolder {
            get {
                return ResourceManager.GetString("ProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The absolute location of the project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectFolderDescription {
            get {
                return ResourceManager.GetString("ProjectFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Home に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectHome {
            get {
                return ResourceManager.GetString("ProjectHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The base location for all files in the project に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectHomeDescription {
            get {
                return ResourceManager.GetString("ProjectHomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Project Properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProjectProperties {
            get {
                return ResourceManager.GetString("ProjectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Publish に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If the file should be included in the files which are published. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PublishDescription {
            get {
                return ResourceManager.GetString("PublishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The project file &apos;{0}&apos; has been modified outside of Visual Studio.  Do you want to reload the project? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QueryReloadNestedProject {
            get {
                return ResourceManager.GetString("QueryReloadNestedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quiet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Quiet {
            get {
                return ResourceManager.GetString("Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A reference to component &apos;{0}&apos; cannot be added. A reference to the component already exists in the project. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReferenceAlreadyExists {
            get {
                return ResourceManager.GetString("ReferenceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reference Properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReferenceProperties {
            get {
                return ResourceManager.GetString("ReferenceProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   References に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReferencesNodeName {
            get {
                return ResourceManager.GetString("ReferencesNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Name) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RefName {
            get {
                return ResourceManager.GetString("RefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display name of the reference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RefNameDescription {
            get {
                return ResourceManager.GetString("RefNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename directory failed. {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RenameFolder {
            get {
                return ResourceManager.GetString("RenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RTL_False に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RTL {
            get {
                return ResourceManager.GetString("RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveCaption {
            get {
                return ResourceManager.GetString("SaveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save modified documents? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveModifiedDocuments {
            get {
                return ResourceManager.GetString("SaveModifiedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The project file can only be saved into the project location &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveOfProjectFileOutsideCurrentDirectory {
            get {
                return ResourceManager.GetString("SaveOfProjectFileOutsideCurrentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Script arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScriptArguments {
            get {
                return ResourceManager.GetString("ScriptArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arguments passed to the script on launch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScriptArgumentsDescription {
            get {
                return ResourceManager.GetString("ScriptArgumentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **SeeActivityLog** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SeeActivityLog {
            get {
                return ResourceManager.GetString("SeeActivityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **SourceUrlNotFound** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SourceUrlNotFound {
            get {
                return ResourceManager.GetString("SourceUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error opening specified view &apos;{0}&apos; using standard editor. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StandardEditorViewError {
            get {
                return ResourceManager.GetString("StandardEditorViewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Startup file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartupFile {
            get {
                return ResourceManager.GetString("StartupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The startup file which is launched when running or debugging に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartupFileDescription {
            get {
                return ResourceManager.GetString("StartupFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start web browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartWebBrowser {
            get {
                return ResourceManager.GetString("StartWebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   True to start the web browser when launching に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartWebBrowserDescription {
            get {
                return ResourceManager.GetString("StartWebBrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **UnableToRemoveFile** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnableToRemoveFile {
            get {
                return ResourceManager.GetString("UnableToRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **UnexpectedUpgradeError** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedUpgradeError {
            get {
                return ResourceManager.GetString("UnexpectedUpgradeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Unknown) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnknownInParentheses {
            get {
                return ResourceManager.GetString("UnknownInParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **UpgradeCannotCheckOutProject** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpgradeCannotCheckOutProject {
            get {
                return ResourceManager.GetString("UpgradeCannotCheckOutProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **UpgradeCannotLoadProject** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpgradeCannotLoadProject {
            get {
                return ResourceManager.GetString("UpgradeCannotLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   **UpgradeNotRequired** に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpgradeNotRequired {
            get {
                return ResourceManager.GetString("UpgradeNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You are trying to use an item that has already been deleted or that does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UseOfDeletedItemError {
            get {
                return ResourceManager.GetString("UseOfDeletedItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft .NET Framework v1.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string v1 {
            get {
                return ResourceManager.GetString("v1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft .NET Framework v1.1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string v11 {
            get {
                return ResourceManager.GetString("v11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft .NET Framework v2.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string v2 {
            get {
                return ResourceManager.GetString("v2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft .NET Framework v3.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string v3 {
            get {
                return ResourceManager.GetString("v3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft .NET Framework v3.5 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string v35 {
            get {
                return ResourceManager.GetString("v35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft .NET Framework v4.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string v4 {
            get {
                return ResourceManager.GetString("v4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Feed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WebPiFeed {
            get {
                return ResourceManager.GetString("WebPiFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The WebPI Feed that contains this reference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WebPiFeedDescription {
            get {
                return ResourceManager.GetString("WebPiFeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Product ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WebPiProduct {
            get {
                return ResourceManager.GetString("WebPiProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The product ID that for this web reference に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WebPiProductDescription {
            get {
                return ResourceManager.GetString("WebPiProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows Application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WinExe {
            get {
                return ResourceManager.GetString("WinExe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WorkingDirectory {
            get {
                return ResourceManager.GetString("WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The working directory when launching に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WorkingDirectoryDescription {
            get {
                return ResourceManager.GetString("WorkingDirectoryDescription", resourceCulture);
            }
        }
    }
}
